export enum MemoryDataType {
    INT =       'int',
    INT32 =     'int32',
    INT64 =     'int64',
    UINT32 =    'uint32',
    UINT64 =    'unint64',
    FLOAT =     'float',
    DOUBLE =    'double',
    LONG =      'long',
    BYTE =      'byte',
    PTR =       'ptr',
    POINTER =   'pointer',
    DWORD =     'dword',
    BOOL =      'bool',
    BOOLEAN =   'boolean',
    STRING =    'string',
    STR =       'str',
    VEC3 =      'vec3',
    VECTOR3 =   'vector3',
    VEC4 =      'vec4',
    VECTOR4 =   'vector4'
}